services:
  redis:
    image: redis:7-alpine
    container_name: notification_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: notification_celery_worker
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - .:/app
    depends_on:
      - redis

  ngrok:
    image: ngrok/ngrok:latest
    container_name: notification_ngrok
    restart: unless-stopped
    ports:
      - "4040:4040"
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}
    command:
      - "http"
      - "--url=rely-fossilisable-lukas.ngrok-free.dev"
      - "host.docker.internal:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  redis_data: