"""split inbound messages into epics tables

Revision ID: 4b9e88717b42
Revises: 2241a2b54a8e
Create Date: 2026-05-04 04:01:11.423666+00:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4b9e88717b42"
down_revision = "2241a2b54a8e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_messages_raw",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=50), nullable=False),
        sa.Column("candidate_id", sa.String(length=255), nullable=True),
        sa.Column("sender_address", sa.String(length=255), nullable=False),
        sa.Column(
            "channel",
            postgresql.ENUM("EMAIL", "SMS", "WHATSAPP", "CHAT", name="inbound_channel_enum", create_type=False),
            nullable=False,
        ),
        sa.Column("provider_message_id", sa.String(length=255), nullable=False),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("retention_date", sa.DateTime(), nullable=True),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["owner_id"], ["tenant_users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "provider_message_id", name="uq_tenant_provider_msg"),
    )
    op.create_table(
        "inbound_messages_parsed",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("raw_message_id", sa.UUID(), nullable=False),
        sa.Column("parsed_content", sa.Text(), nullable=True),
        sa.Column("parser_version", sa.String(length=50), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "RECEIVED",
                "PARSED",
                "INTENT_DETECTED",
                "FAILED",
                "IGNORED",
                name="inbound_status_enum",
                create_type=False
            ),
            nullable=False,
        ),
        sa.Column("failure_reason", sa.Text(), nullable=True),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("reference_id", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["raw_message_id"], ["inbound_messages_raw.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("raw_message_id"),
    )
    op.create_index(
        op.f("ix_inbound_messages_parsed_reference_id"),
        "inbound_messages_parsed",
        ["reference_id"],
        unique=False,
    )
    op.create_table(
        "inbound_workflow_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("intent_id", sa.UUID(), nullable=False),
        sa.Column("action_name", sa.String(length=255), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["intent_id"], ["inbound_intents.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.drop_constraint(op.f("inbound_intents_message_id_fkey"), "inbound_intents", type_="foreignkey")
    op.drop_index(op.f("ix_inbound_messages_reference_id"), table_name="inbound_messages")
    op.drop_table("inbound_messages")
    op.execute("DELETE FROM inbound_intents")
    op.add_column("inbound_intents", sa.Column("parsed_message_id", sa.UUID(), nullable=False))
    op.add_column("inbound_intents", sa.Column("needs_review", sa.Boolean(), nullable=False))
    op.drop_constraint(op.f("inbound_intents_message_id_key"), "inbound_intents", type_="unique")
    op.create_unique_constraint(None, "inbound_intents", ["parsed_message_id"])
    op.create_foreign_key(
        None,
        "inbound_intents",
        "inbound_messages_parsed",
        ["parsed_message_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("inbound_intents", "message_id")
    op.drop_index(op.f("idx_embeddings_created"), table_name="notification_embeddings")
    op.drop_index(op.f("idx_embeddings_hash"), table_name="notification_embeddings")
    op.drop_index(op.f("idx_embeddings_tenant_user"), table_name="notification_embeddings")
    op.create_index(
        op.f("ix_notification_embeddings_content_hash"),
        "notification_embeddings",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_embeddings_created_at"),
        "notification_embeddings",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_embeddings_tenant_id"),
        "notification_embeddings",
        ["tenant_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_embeddings_user_id"),
        "notification_embeddings",
        ["user_id"],
        unique=False,
    )
    op.drop_index(op.f("idx_events_created"), table_name="notification_events")
    op.drop_index(op.f("idx_events_notification_id"), table_name="notification_events")
    op.drop_index(op.f("idx_events_type"), table_name="notification_events")
    op.create_index(
        op.f("ix_notification_events_created_at"),
        "notification_events",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_events_event_type"),
        "notification_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_notification_events_notification_id"),
        "notification_events",
        ["notification_id"],
        unique=False,
    )
    op.drop_index(op.f("idx_notifications_idempotency"), table_name="notifications")
    op.create_index(
        op.f("ix_notifications_idempotency_key"), "notifications", ["idempotency_key"], unique=False
    )
    op.drop_index(op.f("idx_provider_health_channel"), table_name="provider_health")
    op.drop_index(op.f("idx_provider_health_is_healthy"), table_name="provider_health")
    op.create_index(
        op.f("ix_provider_health_channel"), "provider_health", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_provider_health_is_healthy"), "provider_health", ["is_healthy"], unique=False
    )
    op.drop_constraint(op.f("tenants_api_key_hash_key"), "tenants", type_="unique")
    op.drop_constraint(op.f("tenants_username_key"), "tenants", type_="unique")
    op.drop_index(op.f("idx_user_engagement_channel"), table_name="user_engagement")
    op.drop_index(op.f("idx_user_engagement_tenant_user"), table_name="user_engagement")
    op.create_index(
        op.f("ix_user_engagement_channel"), "user_engagement", ["channel"], unique=False
    )
    op.create_index(
        op.f("ix_user_engagement_tenant_id"), "user_engagement", ["tenant_id"], unique=False
    )
    op.create_index(
        op.f("ix_user_engagement_user_id"), "user_engagement", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_engagement_user_id"), table_name="user_engagement")
    op.drop_index(op.f("ix_user_engagement_tenant_id"), table_name="user_engagement")
    op.drop_index(op.f("ix_user_engagement_channel"), table_name="user_engagement")
    op.create_index(
        op.f("idx_user_engagement_tenant_user"),
        "user_engagement",
        ["tenant_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_user_engagement_channel"), "user_engagement", ["channel"], unique=False
    )
    op.create_unique_constraint(
        op.f("tenants_username_key"), "tenants", ["username"], postgresql_nulls_not_distinct=False
    )
    op.create_unique_constraint(
        op.f("tenants_api_key_hash_key"),
        "tenants",
        ["api_key_hash"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_index(op.f("ix_provider_health_is_healthy"), table_name="provider_health")
    op.drop_index(op.f("ix_provider_health_channel"), table_name="provider_health")
    op.create_index(
        op.f("idx_provider_health_is_healthy"), "provider_health", ["is_healthy"], unique=False
    )
    op.create_index(
        op.f("idx_provider_health_channel"), "provider_health", ["channel"], unique=False
    )
    op.drop_index(op.f("ix_notifications_idempotency_key"), table_name="notifications")
    op.create_index(
        op.f("idx_notifications_idempotency"), "notifications", ["idempotency_key"], unique=False
    )
    op.drop_index(op.f("ix_notification_events_notification_id"), table_name="notification_events")
    op.drop_index(op.f("ix_notification_events_event_type"), table_name="notification_events")
    op.drop_index(op.f("ix_notification_events_created_at"), table_name="notification_events")
    op.create_index(op.f("idx_events_type"), "notification_events", ["event_type"], unique=False)
    op.create_index(
        op.f("idx_events_notification_id"), "notification_events", ["notification_id"], unique=False
    )
    op.create_index(op.f("idx_events_created"), "notification_events", ["created_at"], unique=False)
    op.drop_index(op.f("ix_notification_embeddings_user_id"), table_name="notification_embeddings")
    op.drop_index(
        op.f("ix_notification_embeddings_tenant_id"), table_name="notification_embeddings"
    )
    op.drop_index(
        op.f("ix_notification_embeddings_created_at"), table_name="notification_embeddings"
    )
    op.drop_index(
        op.f("ix_notification_embeddings_content_hash"), table_name="notification_embeddings"
    )
    op.create_index(
        op.f("idx_embeddings_tenant_user"),
        "notification_embeddings",
        ["tenant_id", "user_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_embeddings_hash"), "notification_embeddings", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("idx_embeddings_created"), "notification_embeddings", ["created_at"], unique=False
    )
    op.add_column(
        "inbound_intents", sa.Column("message_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "inbound_intents", type_="foreignkey")
    op.create_foreign_key(
        op.f("inbound_intents_message_id_fkey"),
        "inbound_intents",
        "inbound_messages",
        ["message_id"],
        ["id"],
    )
    op.drop_constraint(None, "inbound_intents", type_="unique")
    op.create_unique_constraint(
        op.f("inbound_intents_message_id_key"),
        "inbound_intents",
        ["message_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_column("inbound_intents", "needs_review")
    op.drop_column("inbound_intents", "parsed_message_id")
    op.create_table(
        "inbound_messages",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("sender_address", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column(
            "channel",
            postgresql.ENUM("EMAIL", "SMS", "WHATSAPP", "CHAT", name="inbound_channel_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "raw_payload",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("parsed_content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("reference_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM(
                "RECEIVED",
                "PARSED",
                "INTENT_DETECTED",
                "FAILED",
                "IGNORED",
                name="inbound_status_enum",
            ),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "metadata_json",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
        sa.Column("owner_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["tenant_users.id"],
            name=op.f("inbound_messages_owner_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            name=op.f("inbound_messages_tenant_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("inbound_messages_pkey")),
    )
    op.create_index(
        op.f("ix_inbound_messages_reference_id"), "inbound_messages", ["reference_id"], unique=False
    )
    op.drop_table("inbound_workflow_events")
    op.drop_index(
        op.f("ix_inbound_messages_parsed_reference_id"), table_name="inbound_messages_parsed"
    )
    op.drop_table("inbound_messages_parsed")
    op.drop_table("inbound_messages_raw")
    # ### end Alembic commands ###
