"""add_owner_id_to_notifications

Revision ID: 7e68ac545ef0
Revises: 4b9e88717b42
Create Date: 2026-05-04 11:20:41.625336+00:00

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "7e68ac545ef0"
down_revision = "4b9e88717b42"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("notifications", sa.Column("owner_id", sa.UUID(), nullable=True))
    op.create_foreign_key(
        None, "notifications", "tenant_users", ["owner_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "notifications", type_="foreignkey")
    op.drop_column("notifications", "owner_id")
    # ### end Alembic commands ###
