"""add_inbound_message_tables

Revision ID: 6d74fd46f831
Revises: b1f3a7d9c8e4
Create Date: 2026-04-23 09:11:00.742765+00:00

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "6d74fd46f831"
down_revision = "b1f3a7d9c8e4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbound_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.String(length=50), nullable=False),
        sa.Column("sender_address", sa.String(length=255), nullable=False),
        sa.Column(
            "channel",
            sa.Enum("EMAIL", "SMS", "WHATSAPP", "CHAT", name="inbound_channel_enum"),
            nullable=False,
        ),
        sa.Column("raw_payload", sa.JSON(), nullable=False),
        sa.Column("parsed_content", sa.Text(), nullable=True),
        sa.Column("reference_id", sa.String(length=255), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "RECEIVED",
                "PARSED",
                "INTENT_DETECTED",
                "FAILED",
                "IGNORED",
                name="inbound_status_enum",
            ),
            nullable=False,
        ),
        sa.Column("metadata_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["tenant_id"],
            ["tenants.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_inbound_messages_reference_id"), "inbound_messages", ["reference_id"], unique=False
    )
    op.create_table(
        "inbound_intents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column(
            "intent",
            sa.Enum("ACCEPT", "REJECT", "REQUEST", "QUERY", "UNKNOWN", name="intent_category_enum"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "detection_method",
            sa.Enum("RULES", "LLM", "MANUAL", name="detection_method_enum"),
            nullable=False,
        ),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["inbound_messages.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("message_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("inbound_intents")
    op.drop_index(op.f("ix_inbound_messages_reference_id"), table_name="inbound_messages")
    op.drop_table("inbound_messages")
    # ### end Alembic commands ###
